---
label: Site Configuration
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: Site title
  config:
    required: true
- type: text
  name: domain
  label: Domain
  description: The domain of your site, including the protocol, e.g. https://mysite.com/
- type: file
  name: favicon
  label: Favicon
  description: A square icon that represents your website
- type: select
  name: palette
  label: Color Palette
  description: The color palette of the site
  default: blue
  config:
    required: true
    source:
      type: custom
    options:
    - blue
    - cyan
    - green
    - orange
    - purple
- type: select
  name: base_font
  label: Font
  default: nunito-sans
  config:
    required: true
    source:
      type: custom
    options:
    - fira-sans
    - nunito-sans
    - system-sans
- type: field_group
  name: header
  label: Header Configuration
  fields:
  - type: include
    name: include_header
    label: Header Configuration
    template: header
- type: field_group
  name: footer
  label: Footer Configuration
  fields:
  - type: include
    name: include_footer
    label: Footer Configuration
    template: footer
pages:
- site-metadata.json
